#!/bin/sh
# Define where host lists are kept
hostofFolder="/etc/hostof"
hostListFolder="$hostofFolder/hostlist"
# Define my host list folder
myHostListFolder="$hostListFolder/$(whoami)"

# Ensure my hosts directory exists
mkdir -p "$myHostListFolder"
# Ensure my hosts directory is private
chmod 700 "$myHostListFolder"

# Remove old references to the user
#+if my hosts file exists
if [ -e "$myHostListFolder/hosts" ]; then awk -F ^ "toupper(\$1)!~/"$(echo "$1" | awk "{ print toupper(\$0) }")"/" "$myHostListFolder/hosts" > "$myHostListFolder/hosts.new"; mv "$myHostListFolder/hosts.new" "$myHostListFolder/hosts"; fi

# Put the name and host in my hosts file, delimited by ^
echo "$1"^"$2" >> "$myHostListFolder/hosts"
# Ensure my hosts file is private
chmod 600 "$myHostListFolder/hosts"
