#!/bin/sh
# Add to the saved list of hosts associated with a name

# Define where host lists are kept
hostofFolder="/etc/hostof"
hostListFolder="$hostofFolder/hostlist"
# Define my host list folder
myHostListFolder="$hostListFolder/$(whoami)"
# Define my host list file
myHostListFile="$myHostListFolder/hosts"

# Ensure my hosts directory exists
mkdir -p "$myHostListFolder"
# Ensure my hosts directory is private
chmod 700 "$myHostListFolder"

# Ensure my hosts file exists
touch "$myHostListFile"
# Ensure my hosts file is private
chmod 600 "$myHostListFile"

SEPARATOR=" "

# Remove old references to the user
awk -F "$SEPARATOR" "toupper(\$1)!~toupper(\"$1\")" "$myHostListFile" > "$myHostListFile.new";
mv "$myHostListFile.new" "$myHostListFile";

# Put the name and host in my hosts file, delimited by SEPARATOR
echo "$1""$SEPARATOR""$2" >> "$myHostListFile"
