#!/bin/sh
# Add to the saved list of logins associated with a name

# Define where login list is kept
loginListFolder="$HOME/.loginof"
# Define my login list file
loginListFileName="logins"
loginListFileLocation="$loginListFolder/$loginListFileName"

# Ensure my logins directory exists
mkdir -p "$loginListFolder"
# Ensure my logins directory is private
chmod ug=rwx,o= "$loginListFolder"

# Ensure my logins file exists
touch "$loginListFileLocation"
# Ensure my logins file is private
chmod ug=rw,o= "$loginListFileLocation"

SEPARATOR=":"

# Remove old references to the user
awk -F "$SEPARATOR" 'toupper($1)!~toupper("'"$1"'")' "$loginListFileLocation" > "$loginListFileLocation.new";
mv "$loginListFileLocation.new" "$loginListFileLocation";

# Put the name and login in my logins file, delimited by SEPARATOR
echo "$1""$SEPARATOR""$2" >> "$loginListFileLocation"
