#!/bin/sh
# Add to the saved list of logins associated with a name

# Define where login list is kept
LOGINLISTFOLDER="$HOME/.loginof"
# Define my login list file
LOGINLISTFILENAME="logins"
LOGINLISTFILELOCATION="$LOGINLISTFOLDER/$LOGINLISTFILENAME"

# Ensure my logins directory exists
mkdir -p "$LOGINLISTFOLDER"
# Ensure my logins directory is private
chmod ug=rwx,o= "$LOGINLISTFOLDER"

# Ensure my logins file exists
touch "$LOGINLISTFILELOCATION"
# Ensure my logins file is private
chmod ug=rw,o= "$LOGINLISTFILELOCATION"

SEPARATOR=":"

# Remove old references to the user
awk -F "$SEPARATOR" 'toupper($1)!~toupper("'"$1"'")' "$LOGINLISTFILELOCATION" > "$LOGINLISTFILELOCATION.new";
mv "$LOGINLISTFILELOCATION.new" "$LOGINLISTFILELOCATION";

# Put the name and login in my logins file, delimited by SEPARATOR
echo "$1""$SEPARATOR""$2" >> "$loginListFileLocation"
