#!/bin/sh
# Installs loginof executables and folders

# Set locations
listLocation="$HOME/.loginof"
executablesLocation="$HOME/.local/bin"
globalExecutablesLocation="/opt/loginof"

# Perform local installation

# Ensure folders exist
mkdir -p "$listLocation" "$executablesLocation" && \

# Ensure only the user can access their list
chmod u=rwx,g=rx,o= "$listLocation" && \

# Put the scripts in their proper location
cp loginof rmloginof addloginof "$executablesLocation" && \

# Make the scripts executable and readable
chmod a+xr "$executablesLocation"/* && \

# Copy this installer
cp $0 "$executablesLocation" && \

# Make the scripts executable and readable
chmod a+xr "$executablesLocation"/* && \

# Report success
echo "loginof successfully installed locally" ||
# Or report failure
{ echo "loginof NOT successfully installed locally"; exit 2; }


# Ask user if they want to install globally

echo "Do you have sudo access and want to install system-wide? [Y]"

read REPLY

if [ "$REPLY" = "Y" ]; then
# Perform global installation

# Ensure folder exists
sudo mkdir -p "$globalExecutablesLocation" && \

# Ensure everyone can see the executables
sudo chmod u=rwx,go=rx "$globalExecutablesLocation" && \

# Put the scripts in their proper location
sudo cp loginof rmloginof addloginof "$globalExecutablesLocation" && \

# Make the scripts executable and readable
sudo chmod a+xr "$globalExecutablesLocation"/* && \

# Copy this installer
sudo cp $0 "$globalExecutablesLocation" && \

# Make the scripts executable and readable
sudo chmod a+xr "$globalExecutablesLocation"/* && \

# Append to every user's PATH
echo 'PATH=$PATH:'"$globalExecutablesLocation" | sudo tee -a /etc/profile >/dev/null && \

# Report success
echo "loginof successfully installed globally" || \
# Or report failure
{ echo "loginof NOT successfully installed globally"; exit 1; }
fi
