#!/bin/sh
# Installs loginof executables and folders

# Set locations
LISTLOCATION="$HOME/.loginof"
EXECUTABLESLOCATION="$HOME/.local/bin"
GLOBALEXECUTABLESLOCATION="/opt/loginof"

# Perform local installation

# Ensure folders exist
mkdir -p "$LISTLOCATION" "$EXECUTABLESLOCATION" && \

# Ensure only the user can access their list
chmod u=rwx,g=rx,o= "$LISTLOCATION" && \

# Put the scripts in their proper location
cp loginof rmloginof addloginof "$EXECUTABLESLOCATION" && \

# Make the scripts executable and readable
chmod a+xr "$EXECUTABLESLOCATION"/* && \

# Ensure the executables folder is in the PATH
echo 'PATH="$PATH":'"$EXECUTABLESLOCATION" | tee -a ~/.profile >/dev/null && \
PATH="$PATH":"$EXECUTABLESLOCATION" && \

# Copy this installer
cp $0 "$EXECUTABLESLOCATION" && \

# Make the scripts executable and readable
chmod a+xr "$EXECUTABLESLOCATION"/* && \

# Report success
echo "loginof successfully installed locally" ||
# Or report failure
{ echo "loginof NOT successfully installed locally"; exit 2; }


# Ask user if they want to install globally

echo "Do you have sudo access and want to install system-wide? [Y]"

read REPLY

if [ "$REPLY" = "Y" ]; then
# Perform global installation

# Ensure folder exists
sudo mkdir -p "$GLOBALEXECUTABLESLOCATION" && \

# Ensure everyone can see the executables
sudo chmod u=rwx,go=rx "$GLOBALEXECUTABLESLOCATION" && \

# Put the scripts in their proper location
sudo cp loginof rmloginof addloginof "$GLOBALEXECUTABLESLOCATION" && \

# Make the scripts executable and readable
sudo chmod a+xr "$GLOBALEXECUTABLESLOCATION"/* && \

# Append to every user's PATH
echo 'PATH="$PATH":'"$GLOBALEXECUTABLESLOCATION" | sudo tee -a /etc/profile >/dev/null && \
PATH="$PATH":"$GLOBALEXECUTABLESLOCATION" && \

# Copy this installer
sudo cp $0 "$GLOBALEXECUTABLESLOCATION" && \

# Make the scripts executable and readable
sudo chmod a+xr "$GLOBALEXECUTABLESLOCATION"/* && \

# Report success
echo "loginof successfully installed globally" || \
# Or report failure
{ echo "loginof NOT successfully installed globally"; exit 1; }
fi
