#!/bin/sh
# Installs loginof executables and folders

# Set folder locations
listsLocation="/etc/loginof/loginlist"
executablesLocation="/opt/loginof"

# Ensure folders exist
sudo mkdir -p "$listsLocation" "$executablesLocation" && \

# Ensure everyone can make their own list folder but not edit others'
sudo chmod a=rwx "$listsLocation" && \

# Put the scripts in their proper location
sudo cp loginof addloginof "$executablesLocation" && \

# Copy this installer
sudo cp $0 "$executablesLocation" && \

# Make the scripts executable and readable
sudo chmod a=xr "$executablesLocation"/* && \

# Report success and useful tips...
echo "loginof successfully installed!
You may want to add \"$executablesLocation\" to your PATH variable automatically in your shell profile or rc file
EG: 
echo 'PATH=\$PATH:'$executablesLocation | tee -a ~/.profile
Or: 
echo 'PATH=\$PATH:'$executablesLocation | sudo tee -a ~/.profile /etc/profile" || \
# Or report failure
{ echo "loginof NOT successfully installed"; exit 1; }
