#!/bin/sh
# Add to the saved list of logins associated with a name

# Define where login list is kept
LOGINLISTFOLDER="$HOME/.loginof"
# Define my login list file
LOGINLISTFILE="$LOGINLISTFOLDER/logins"

# Ensure my logins directory exists
mkdir -p "$LOGINLISTFOLDER"
# Ensure my logins directory is private
chmod ug=rwx,o= "$LOGINLISTFOLDER"

# Ensure my logins file exists
touch "$LOGINLISTFILE"
# Ensure my logins file is private
chmod ug=rw,o= "$LOGINLISTFILE"

SEPARATOR=":"

# Remove old references to the user
awk -F "$SEPARATOR" "toupper(\$1)!~toupper(\"$1\")" "$LOGINLISTFILE" > "$LOGINLISTFILE.new";
mv "$LOGINLISTFILE.new" "$LOGINLISTFILE";
